In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/Manju410/MLPractice/main/data/CarDetails_Cleanup.csv')
df.head()

   name  year  ...  owner_Test Drive Car  owner_Third Owner
0     7  2014  ...                     0                  0
1    11  2014  ...                     0                  0
2     3  2006  ...                     0                  1
3     4  2010  ...                     0                  0
4     7  2007  ...                     0                  0

[5 rows x 23 columns]

In [ ]:
df.shape

(8128, 23)

In [ ]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'mileage', 'engine',
       'max_power', 'torque', 'seats', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol', 'seller_type_Dealer', 'seller_type_Individual',
       'seller_type_Trustmark Dealer', 'transmission_Automatic',
       'transmission_Manual', 'owner_First Owner',
       'owner_Fourth & Above Owner', 'owner_Second Owner',
       'owner_Test Drive Car', 'owner_Third Owner'],
      dtype='object')

In [ ]:
X = df.drop(['selling_price'],axis=1)
y= df.selling_price

In [ ]:
X.shape,y.shape

((8128, 22), (8128,))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1234)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mmscaler = MinMaxScaler()

In [ ]:
X_train.head()

      name  year  ...  owner_Test Drive Car  owner_Third Owner
7094     4  2019  ...                     0                  0
2041     4  2017  ...                     0                  0
1524     7  2017  ...                     0                  0
2994     7  2008  ...                     0                  0
3726     4  2012  ...                     0                  0

[5 rows x 22 columns]

In [ ]:
continuoscol = ['name','year','km_driven','mileage','engine','max_power','torque','seats']

In [ ]:
scaler = mmscaler.fit(X_train[continuoscol])

In [ ]:
scaler.data_max_

array([13.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
scaler.data_min_

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
scaled_vals = scaler.transform(X_train[continuoscol])

In [ ]:
scaled_vals1 = scaler.transform(X_test[continuoscol])

In [ ]:
X_test_scaled = pd.DataFrame(scaled_vals1,columns=continuoscol,index=X_test.index)
X_test_scaled.head()

          name      year  km_driven  ...  max_power    torque  seats
362   0.615385  0.810811   0.016666  ...   0.425000  0.503953   0.25
1024  0.923077  0.675676   0.079999  ...   0.170000  0.010457   0.25
2273  1.000000  0.756757   0.056033  ...   0.228795  0.208485   0.25
3303  0.000000  0.891892   0.131999  ...   0.184350  0.213849   0.50
90    0.538462  0.729730   0.029333  ...   0.145500  0.092068   0.25

[5 rows x 8 columns]

In [ ]:
X_train_scaled = pd.DataFrame(scaled_vals,columns=continuoscol,index=X_train.index)
X_train_scaled.head()

          name      year  km_driven  ...  max_power    torque  seats
7094  0.307692  0.972973   0.013066  ...   0.221750  0.274037   0.25
2041  0.307692  0.918919   0.019999  ...   0.204575  0.140143   0.25
1524  0.538462  0.918919   0.033333  ...   0.118250  0.081867   0.25
2994  0.538462  0.675676   0.066666  ...   0.214500  0.139250   0.25
3726  0.307692  0.783784   0.053333  ...   0.315800  0.325172   0.25

[5 rows x 8 columns]

In [ ]:
X_train.drop(columns=continuoscol,axis=1,inplace=True)

In [ ]:
X_train.insert(0,X_train_scaled.columns[0],X_train_scaled[X_train_scaled.columns[0]])
X_train.insert(1,X_train_scaled.columns[1],X_train_scaled[X_train_scaled.columns[1]])
X_train.insert(2,X_train_scaled.columns[2],X_train_scaled[X_train_scaled.columns[2]])
X_train.insert(3,X_train_scaled.columns[3],X_train_scaled[X_train_scaled.columns[3]])
X_train.insert(4,X_train_scaled.columns[4],X_train_scaled[X_train_scaled.columns[4]])
X_train.insert(5,X_train_scaled.columns[5],X_train_scaled[X_train_scaled.columns[5]])
X_train.insert(6,X_train_scaled.columns[6],X_train_scaled[X_train_scaled.columns[6]])
X_train.insert(7,X_train_scaled.columns[7],X_train_scaled[X_train_scaled.columns[7]])

In [ ]:
X_train.head()

          name      year  ...  owner_Test Drive Car  owner_Third Owner
7094  0.307692  0.972973  ...                     0                  0
2041  0.307692  0.918919  ...                     0                  0
1524  0.538462  0.918919  ...                     0                  0
2994  0.538462  0.675676  ...                     0                  0
3726  0.307692  0.783784  ...                     0                  0

[5 rows x 22 columns]

In [ ]:
X_test.drop(columns=continuoscol,axis=1,inplace=True)
X_test.insert(0,X_test_scaled.columns[0],X_test_scaled[X_test_scaled.columns[0]])
X_test.insert(1,X_test_scaled.columns[1],X_test_scaled[X_test_scaled.columns[1]])
X_test.insert(2,X_test_scaled.columns[2],X_test_scaled[X_test_scaled.columns[2]])
X_test.insert(3,X_test_scaled.columns[3],X_test_scaled[X_test_scaled.columns[3]])
X_test.insert(4,X_test_scaled.columns[4],X_test_scaled[X_test_scaled.columns[4]])
X_test.insert(5,X_test_scaled.columns[5],X_test_scaled[X_test_scaled.columns[5]])
X_test.insert(6,X_test_scaled.columns[6],X_test_scaled[X_test_scaled.columns[6]])
X_test.insert(7,X_test_scaled.columns[7],X_test_scaled[X_test_scaled.columns[7]])

In [ ]:
X_test.head()

          name      year  ...  owner_Test Drive Car  owner_Third Owner
362   0.615385  0.810811  ...                     0                  0
1024  0.923077  0.675676  ...                     0                  1
2273  1.000000  0.756757  ...                     0                  0
3303  0.000000  0.891892  ...                     0                  0
90    0.538462  0.729730  ...                     0                  0

[5 rows x 22 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
linmodel = LinearRegression()
linmodel.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = linmodel.predict(X_test)

In [ ]:
df_coeff = pd.DataFrame({'columns':X_train.columns,'coeff':linmodel.coef_})
df_coeff

                         columns         coeff
0                           name  2.220717e+05
1                           year  1.130496e+06
2                      km_driven -2.244099e+06
3                        mileage  4.667297e+05
4                         engine  2.024654e+05
5                      max_power  4.834810e+06
6                         torque  2.808284e+05
7                          seats -3.966385e+05
8                       fuel_CNG  4.671983e+17
9                    fuel_Diesel  4.671983e+17
10                      fuel_LPG  4.671983e+17
11                   fuel_Petrol  4.671983e+17
12            seller_type_Dealer  1.370421e+18
13        seller_type_Individual  1.370421e+18
14  seller_type_Trustmark Dealer  1.370421e+18
15        transmission_Automatic -1.489677e+17
16           transmission_Manual -1.489677e+17
17             owner_First Owner  1.771873e+19
18    owner_Fourth & Above Owner  1.771873e+19
19            owner_Second Owner  1.771873e+19
20          owner_Test Drive Car  1.771873e+19
21             owner_Third Owner  1.771873e+19

In [ ]:
residuals = pd.DataFrame({'pred':y_pred,'actul':y_test})
residuals.head()

           pred    actul
362   2142208.0  1550000
1024    28672.0   175000
2273   544768.0   210000
3303    12288.0   500000
90     581632.0   225000

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_pred,y_test)

0.5685964223748708