In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Manju410/MLPractice/main/data/Cardetails.csv')
df.head()

                           name  year  ...                    torque  seats
0        Maruti Swift Dzire VDI  2014  ...            190Nm@ 2000rpm    5.0
1  Skoda Rapid 1.5 TDI Ambition  2014  ...       250Nm@ 1500-2500rpm    5.0
2      Honda City 2017-2020 EXi  2006  ...     12.7@ 2,700(kgm@ rpm)    5.0
3     Hyundai i20 Sportz Diesel  2010  ...  22.4 kgm at 1750-2750rpm    5.0
4        Maruti Swift VXI BSIII  2007  ...     11.5@ 4,500(kgm@ rpm)    5.0

[5 rows x 13 columns]

- Car Details Dataset has 8128 rows and 13 columns

In [3]:
df.shape

(8128, 13)

In [4]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

- mileage, engine, max power, torque columns has null values

In [5]:
df.isna().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

- many of the features has object data type even they have numbers

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

1. identify or seperate target variable (create X,y)
  - 1.1: y = selling price
2. split the data into train and test
  - test:approx 400 - train: remaining(include dev)
  - random state: 578
3. Clean up Dataset(Missing values ,etc)
  - fill by mean(if no outliers: by distribution)
  - fill by median(if outliers are present)
  - fill by mode (if categorical)
4. Convert categorical to numerical
  - One hot encoding(dummies)
  - Label encoding (DONT USE THIS): It is oly for target variable
  - ordinal encoding(range or scaling data)
5. Normalization and standardization if required.
6. Build model
7. Evalute the model

In [7]:
df.head()

                           name  year  ...                    torque  seats
0        Maruti Swift Dzire VDI  2014  ...            190Nm@ 2000rpm    5.0
1  Skoda Rapid 1.5 TDI Ambition  2014  ...       250Nm@ 1500-2500rpm    5.0
2      Honda City 2017-2020 EXi  2006  ...     12.7@ 2,700(kgm@ rpm)    5.0
3     Hyundai i20 Sportz Diesel  2010  ...  22.4 kgm at 1750-2750rpm    5.0
4        Maruti Swift VXI BSIII  2007  ...     11.5@ 4,500(kgm@ rpm)    5.0

[5 rows x 13 columns]

- Seperating name column into Brand and Model columns and droping out name column after seperated

In [8]:
df['Brand'] = df.name.str.split(' ').str[0]
df['Model'] = df.name.str.split(' ').str[1]
df.drop('name',axis=1,inplace=True)

In [9]:
df.head()

   year  selling_price  km_driven  ... seats    Brand  Model
0  2014         450000     145500  ...   5.0   Maruti  Swift
1  2014         370000     120000  ...   5.0    Skoda  Rapid
2  2006         158000     140000  ...   5.0    Honda   City
3  2010         225000     127000  ...   5.0  Hyundai    i20
4  2007         130000     120000  ...   5.0   Maruti  Swift

[5 rows x 14 columns]

- Checking for torque column to additional modification on splitting out torque and speed

In [10]:
df.torque.value_counts()

190Nm@ 2000rpm             530
200Nm@ 1750rpm             445
90Nm@ 3500rpm              405
113Nm@ 4200rpm             223
114Nm@ 4000rpm             171
                          ...
128Nm@ 3100rpm               1
72.9Nm@ 2250rpm              1
155 Nm at 1600-2800 rpm      1
510Nm@ 1600-2800rpm          1
96  Nm at 3000  rpm          1
Name: torque, Length: 441, dtype: int64

- Below integer function will give numerical values from string if not return nan value

In [11]:
from numpy.core.numeric import NaN
import re
def integer(val):
  z = re.match("[0-9.]+",str(val));
  if z: return str(z.group())
  else: return NaN

- applying integer function to mileage, engine, maxpower, torque columns to get numeric data

In [12]:
df.mileage = df.mileage.apply(integer)
df['mileage'] = df['mileage'].astype(float)

In [13]:
df.engine = df.engine.apply(integer)
df['engine'] = df['engine'].astype(float)

In [14]:
df.max_power = df.max_power.apply(integer)
df['max_power'] = df['max_power'].astype(float)

In [15]:
df['Torque'] = df.torque.apply(integer)
df['Torque'] = df['Torque'].astype(float)

- splitting out torque column into torque and speed by below technique and droping out torque column after seperated

In [16]:
df['Speed'] = df['torque'].str.findall(r'([,0-9]+)').str[-1]
df['Speed']= df['Speed'].str.replace(",", "", case = False)
df['Speed']= df['Speed'].astype(float)
df.drop('torque',axis=1,inplace=True)

In [17]:
df.head()

   year  selling_price  km_driven    fuel  ...    Brand  Model Torque   Speed
0  2014         450000     145500  Diesel  ...   Maruti  Swift  190.0  2000.0
1  2014         370000     120000  Diesel  ...    Skoda  Rapid  250.0  2500.0
2  2006         158000     140000  Petrol  ...    Honda   City   12.7  2700.0
3  2010         225000     127000  Diesel  ...  Hyundai    i20   22.4  2750.0
4  2007         130000     120000  Petrol  ...   Maruti  Swift   11.5  4500.0

[5 rows x 15 columns]

In [18]:
#df.drop('Model',axis=1,inplace=True)
#df.drop('Brand',axis=1,inplace=True)

In [19]:
df.Brand.unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [20]:
df.Model.unique()

array(['Swift', 'Rapid', 'City', 'i20', 'Xcent', 'Wagon', '800', 'Etios',
       'Figo', 'Duster', 'Zen', 'KUV', 'Ertiga', 'Alto', 'Verito', 'WR-V',
       'SX4', 'Tigor', 'Baleno', 'Enjoy', 'Omni', 'Vitara', 'Palio',
       'Verna', 'GO', 'Safari', 'Compass', 'Fortuner', 'Innova', 'B',
       'Amaze', 'Pajero', 'Ciaz', 'Jazz', 'A6', 'Corolla', 'New', 'Manza',
       'i10', 'Ameo', 'Indica', 'Vento', 'EcoSport', 'X1', 'Celerio',
       'Polo', 'Eeco', 'Scorpio', 'Freestyle', 'Passat', 'XUV500',
       'Indigo', 'Terrano', 'Creta', 'KWID', 'Santro', 'Q5', 'ES', 'XF',
       'Wrangler', 'Rover', 'S-Class', '5', 'X4', 'Superb', 'E-Class',
       'Hector', 'XC40', 'Q7', 'Elantra', 'XE', 'Nexon', 'CLA', 'Glanza',
       '3', 'Camry', 'XC90', 'Ritz', 'Grand', 'Matiz', 'Zest', 'Getz',
       'Elite', 'Brio', 'Hexa', 'Sunny', 'Micra', 'Ssangyong', 'Quanto',
       'Accent', 'Ignis', 'Marazzo', 'Tiago', 'Thar', 'Sumo', 'Bolero',
       'GL-Class', 'Beat', 'Willys', 'A-Star', 'XUV300', 'Nano', 'GTI',
       'V40', 'CR-V', 'EON', 'RediGO', 'Captiva', 'Fiesta', 'Seltos',
       'Civic', 'Sail', 'Venture', 'Estilo', 'Classic', 'BR-V',
       'Ecosport', 'Aria', 'TUV', 'Bolt', 'Accord', 'Xylo', 'Grande',
       'S-Cross', 'Yaris', 'Tavera', 'Linea', 'Endeavour', 'Aveo',
       'Esteem', 'Triber', 'Fusion', 'Octavia', 'A4', 'XL6', 'Santa',
       'Spark', 'Aspire', 'Punto', 'Optra', 'Mobilio', 'Qualis', 'BRV',
       'X6', 'Cruze', 'GLA', '6', 'NuvoSport', 'Scala', 'Jeep', 'Lodgy',
       'Pulse', 'Supro', 'Ingenio', 'Sonata', 'Renault', 'Kicks', 'Jetta',
       'M-Class', 'Teana', 'Yeti', 'Q3', 'Gurkha', 'Logan', 'A3', 'Dzire',
       'Ikon', 'Fluence', 'Xenon', 'One', '7', 'S60', 'Lancer', 'X7',
       'Premio', 'Fabia', 'Platinum', 'Captur', 'Gypsy', 'Estate',
       'Koleos', 'CLASSIC', 'Harrier', 'Multivan', 'Avventura', 'Laura',
       'Leyland', 'MUX', 'Astra', 'Tucson', 'Winger', 'Spacio', 'Venue',
       'CrossPolo', 'Marshal', 'Kodiaq', 'D-Max', 'X3', 'Land', 'X5',
       '309', 'Trailblazer', 'MU', 'GLC', 'XC60', 'S90', 'S-Presso'],
      dtype=object)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           8128 non-null   int64
 1   selling_price  8128 non-null   int64
 2   km_driven      8128 non-null   int64
 3   fuel           8128 non-null   object
 4   seller_type    8128 non-null   object
 5   transmission   8128 non-null   object
 6   owner          8128 non-null   object
 7   mileage        7907 non-null   float64
 8   engine         7907 non-null   float64
 9   max_power      7912 non-null   float64
 10  seats          7907 non-null   float64
 11  Brand          8128 non-null   object
 12  Model          8128 non-null   object
 13  Torque         7906 non-null   float64
 14  Speed          7906 non-null   float64
dtypes: float64(6), int64(3), object(6)
memory usage: 952.6+ KB

- Creating X and y vaiables

In [22]:
target = 'selling_price'
X = df.drop(target,axis=1)
y = df.loc[:,target]

In [23]:
y.isna().sum()

0

- spliting entire dataset into train and test data which contains 400 records for test and 7.7k for train which will divide train data further into train and dev dataset

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =  train_test_split(X,y,test_size=0.05,random_state=578)
X_train.shape, X_test.shape,y_train.shape

((7721, 14), (407, 14), (7721,))

- Creating numerical columns and Categorical columns using make column selector

In [25]:
from sklearn.compose import make_column_selector
num_col = make_column_selector(dtype_exclude=object)
cat_col = make_column_selector(dtype_include=object)

- importing imputation, column transformer, encoding & pipeline libraries

In [26]:
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.pipeline import make_pipeline

- Creating imputation strategies for mean , median, mode

In [27]:
imp_mean = SimpleImputer(strategy='mean')
imp_median = SimpleImputer(strategy='median')
imp_cat = SimpleImputer(strategy='most_frequent')

- Creating one hot encoding and ordinal encoding strategies

In [28]:
onehot = OneHotEncoder(handle_unknown='ignore')
ordencode = OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)

- Creating column transformer strategy for mean imputaion with one hot encoding and median imputation with ordinal encoding

In [29]:
col_transform_mean = make_column_transformer(
    (make_pipeline(imp_mean),num_col),
    (make_pipeline(imp_cat,onehot),cat_col),
    remainder='passthrough'
)

col_transform_median = make_column_transformer(
    (make_pipeline(imp_median),num_col),
    (make_pipeline(imp_cat,ordencode),cat_col),
    remainder='passthrough'
)

In [30]:
from sklearn.tree import DecisionTreeRegressor

In [31]:
DS_Regressor = DecisionTreeRegressor()

- Creating KFOLD cross validation with 10 splits

In [32]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
kfold = KFold(n_splits=10,shuffle=True,random_state=578)

In [33]:
from sklearn.model_selection import GridSearchCV

In [86]:
Ds_wgt_leaf = np.linspace(0, 2, 10)
parameters={'decisiontreeregressor__min_weight_fraction_leaf': Ds_wgt_leaf}

In [95]:
Ds_minleaf = np.linspace(0, 1, 10)
parameters={'decisiontreeregressor__min_samples_leaf': Ds_minleaf}

In [76]:
Ds_maxdepth = np.linspace(1, 15, 10)
parameters={'decisiontreeregressor__max_depth' : Ds_maxdepth}

In [35]:
parameters={"decisiontreeregressor__splitter":["best","random"],
           "decisiontreeregressor__max_features":["auto","log2","sqrt",None],
           "decisiontreeregressor__max_leaf_nodes":[None,10,20] }

In [96]:
pipe_DS_mean = make_pipeline(col_transform_mean,DS_Regressor)
DS_grid_model = GridSearchCV(pipe_DS_mean,parameters,cv=kfold, n_jobs=-1)

In [97]:
pipe_DS_mean.get_params()

{'columntransformer': ColumnTransformer(remainder='passthrough',
                   transformers=[('pipeline-1',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer())]),
                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7fca2d4304d0>),
                                 ('pipeline-2',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='most_frequent')),
                                                  ('onehotencoder',
                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7fca2d430810>)]),
 'columntransformer__n_jobs': None,
 'columntransformer__pipeline-1': Pipeline(steps=[('simpleimputer', SimpleImputer())]),
 'columntransformer__pipeline-1__memory': None,
 'columntransformer__pipeline-1__simpleimputer': SimpleImputer(),
 'columntransformer__pipeline-1__simpleimputer__add_indicator': False,
 'columntransformer__pipeline-1__simpleimputer__copy': True,
 'columntransformer__pipeline-1__simpleimputer__fill_value': None,
 'columntransformer__pipeline-1__simpleimputer__missing_values': nan,
 'columntransformer__pipeline-1__simpleimputer__strategy': 'mean',
 'columntransformer__pipeline-1__simpleimputer__verbose': 0,
 'columntransformer__pipeline-1__steps': [('simpleimputer', SimpleImputer())],
 'columntransformer__pipeline-1__verbose': False,
 'columntransformer__pipeline-2': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                 ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))]),
 'columntransformer__pipeline-2__memory': None,
 'columntransformer__pipeline-2__onehotencoder': OneHotEncoder(handle_unknown='ignore'),
 'columntransformer__pipeline-2__onehotencoder__categories': 'auto',
 'columntransformer__pipeline-2__onehotencoder__drop': None,
 'columntransformer__pipeline-2__onehotencoder__dtype': numpy.float64,
 'columntransformer__pipeline-2__onehotencoder__handle_unknown': 'ignore',
 'columntransformer__pipeline-2__onehotencoder__sparse': True,
 'columntransformer__pipeline-2__simpleimputer': SimpleImputer(strategy='most_frequent'),
 'columntransformer__pipeline-2__simpleimputer__add_indicator': False,
 'columntransformer__pipeline-2__simpleimputer__copy': True,
 'columntransformer__pipeline-2__simpleimputer__fill_value': None,
 'columntransformer__pipeline-2__simpleimputer__missing_values': nan,
 'columntransformer__pipeline-2__simpleimputer__strategy': 'most_frequent',
 'columntransformer__pipeline-2__simpleimputer__verbose': 0,
 'columntransformer__pipeline-2__steps': [('simpleimputer',
   SimpleImputer(strategy='most_frequent')),
  ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))],
 'columntransformer__pipeline-2__verbose': False,
 'columntransformer__remainder': 'passthrough',
 'columntransformer__sparse_threshold': 0.3,
 'columntransformer__transformer_weights': None,
 'columntransformer__transformers': [('pipeline-1',
   Pipeline(steps=[('simpleimputer', SimpleImputer())]),
   <sklearn.compose._column_transformer.make_column_selector at 0x7fca2d4304d0>),
  ('pipeline-2',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                   ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))]),
   <sklearn.compose._column_transformer.make_column_selector at 0x7fca2d430810>)],
 'columntransformer__verbose': False,
 'columntransformer__verbose_feature_names_out': True,
 'decisiontreeregressor': DecisionTreeRegressor(),
 'decisiontreeregressor__ccp_alpha': 0.0,
 'decisiontreeregressor__criterion': 'squared_error',
 'decisiontreeregressor__max_depth': None,
 'decisiontreeregressor__max_features': None,
 'decisiontreeregressor__max_leaf_nodes': None,
 'decisiontreeregressor__min_impurity_decrease': 0.0,
 'decisiontreeregressor__min_samples_leaf': 1,
 'decisiontreeregressor__min_samples_split': 2,
 'decisiontreeregressor__min_weight_fraction_leaf': 0.0,
 'decisiontreeregressor__random_state': None,
 'decisiontreeregressor__splitter': 'best',
 'memory': None,
 'steps': [('columntransformer', ColumnTransformer(remainder='passthrough',
                     transformers=[('pipeline-1',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer())]),
                                    <sklearn.compose._column_transformer.make_column_selector object at 0x7fca2d4304d0>),
                                   ('pipeline-2',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='most_frequent')),
                                                    ('onehotencoder',
                                                     OneHotEncoder(handle_unknown='ignore'))]),
                                    <sklearn.compose._column_transformer.make_column_selector object at 0x7fca2d430810>)])),
  ('decisiontreeregressor', DecisionTreeRegressor())],
 'verbose': False}

In [98]:
DS_grid_model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning:
60 fits failed out of a total of 100.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 1320, in fit
    X_idx_sorted=X_idx_sorted,
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 244, in fit
    % self.min_samples_leaf
ValueError: min_samples_leaf must be at least 1 or in (0, 0.5], got 0.0

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 1320, in fit
    X_idx_sorted=X_idx_sorted,
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 244, in fit
    % self.min_samples_leaf
ValueError: min_samples_leaf must be at least 1 or in (0, 0.5], got 0.5555555555555556

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 1320, in fit
    X_idx_sorted=X_idx_sorted,
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 244, in fit
    % self.min_samples_leaf
ValueError: min_samples_leaf must be at least 1 or in (0, 0.5], got 0.6666666666666666

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 1320, in fit
    X_idx_sorted=X_idx_sorted,
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 244, in fit
    % self.min_samples_leaf
ValueError: min_samples_leaf must be at least 1 or in (0, 0.5], got 0.7777777777777777

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 1320, in fit
    X_idx_sorted=X_idx_sorted,
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 244, in fit
    % self.min_samples_leaf
ValueError: min_samples_leaf must be at least 1 or in (0, 0.5], got 0.8888888888888888

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 1320, in fit
    X_idx_sorted=X_idx_sorted,
  File "/usr/local/lib/python3.7/dist-packages/sklearn/tree/_classes.py", line 244, in fit
    % self.min_samples_leaf
ValueError: min_samples_leaf must be at least 1 or in (0, 0.5], got 1.0

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:972: UserWarning: One or more of the test scores are non-finite: [       nan 0.50367071 0.29258964 0.20609909 0.14654747        nan
        nan        nan        nan        nan]
  category=UserWarning,

GridSearchCV(cv=KFold(n_splits=10, random_state=578, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('pipeline-1',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer())]),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x7fca2d4304d0>),
                                                                        ('pipeline-2',
                                                                         Pipeline(steps=[('si...
                                                                                         ('onehotencoder',
                                                                                          OneHotEncoder(handle_unknown='ignore'))]),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x7fca2d430810>)])),
                                       ('decisiontreeregressor',
                                        DecisionTreeRegressor())]),
             n_jobs=-1,
             param_grid={'decisiontreeregressor__min_samples_leaf': array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])})

In [39]:
DS_grid_model.best_params_

{'decisiontreeregressor__max_features': 'auto',
 'decisiontreeregressor__max_leaf_nodes': None,
 'decisiontreeregressor__splitter': 'best'}

In [80]:
DS_grid_model.best_params_

{'decisiontreeregressor__max_depth': 11.88888888888889}

In [56]:
DS_grid_model.best_params_

{'decisiontreeregressor__min_samples_leaf': 0.1111111111111111}

In [90]:
DS_grid_model.best_params_

{'decisiontreeregressor__min_weight_fraction_leaf': 0.0}

In [70]:
DS_grid_model.score(X_test,y_test)

0.9420047894599761

In [64]:
DS_grid_model.best_estimator_

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7fca2d161a90>),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7fca2d161750>)])),
                ('decisiontreeregressor', DecisionTreeRegressor())])