In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Basavarajkembhavimath/basavarajkembhavimath.github.io/master/EMP_data-set.csv')
df.head()

   EMPLOYEE_ID  DEPARTMENT_ID     EMAIL  ... REGION_ID_1 REGION_NAME   JOB_ID
0        103.0           60.0   AHUNOLD  ...         1.0      Europe  IT_PROG
1        104.0           60.0    BERNST  ...         1.0      Europe  IT_PROG
2        105.0           60.0   DAUSTIN  ...         1.0      Europe  IT_PROG
3        106.0           60.0  VPATABAL  ...         1.0      Europe  IT_PROG
4        107.0           60.0  DLORENTZ  ...         1.0      Europe  IT_PROG

[5 rows x 21 columns]

In [ ]:
df.shape

(10600, 21)

In [ ]:
df.columns

Index(['EMPLOYEE_ID', 'DEPARTMENT_ID', 'EMAIL', 'FIRST_NAME', 'LAST_NAME',
       'PHONE_NUMBER', 'SALARY', 'DEPARTMENT_ID_1', 'DEPARTMENT_NAME',
       'LOCATION_ID', 'LOCATION_ID_1', 'CITY', 'COUNTRY_ID', 'STATE_PROVINCE',
       'STREET_ADDRESS', 'COUNTRY_ID_1', 'COUNTRY_NAME', 'REGION_ID',
       'REGION_ID_1', 'REGION_NAME', 'JOB_ID'],
      dtype='object')

In [ ]:
df.isna().sum()

EMPLOYEE_ID          0
DEPARTMENT_ID        0
EMAIL                0
FIRST_NAME           0
LAST_NAME            0
PHONE_NUMBER         0
SALARY               0
DEPARTMENT_ID_1      0
DEPARTMENT_NAME      0
LOCATION_ID          0
LOCATION_ID_1        0
CITY                 0
COUNTRY_ID           0
STATE_PROVINCE     100
STREET_ADDRESS       0
COUNTRY_ID_1         0
COUNTRY_NAME         0
REGION_ID            0
REGION_ID_1          0
REGION_NAME          0
JOB_ID               0
dtype: int64

In [ ]:
df.STATE_PROVINCE.unique()

array(['Texas', 'California', 'Washington', 'Ontario', 'Oxford',
       'Bavaria'], dtype=object)

In [ ]:
df.STATE_PROVINCE.value_counts()

California    4600
Oxford        3400
Washington    1800
Texas          500
Ontario        200
Bavaria        100
Name: STATE_PROVINCE, dtype: int64

In [ ]:
df.STATE_PROVINCE.fillna(df.STATE_PROVINCE.value_counts().index[0],inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10600 entries, 0 to 10599
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EMPLOYEE_ID      10600 non-null  float64
 1   DEPARTMENT_ID    10600 non-null  float64
 2   EMAIL            10600 non-null  object
 3   FIRST_NAME       10600 non-null  object
 4   LAST_NAME        10600 non-null  object
 5   PHONE_NUMBER     10600 non-null  object
 6   SALARY           10600 non-null  float64
 7   DEPARTMENT_ID_1  10600 non-null  float64
 8   DEPARTMENT_NAME  10600 non-null  object
 9   LOCATION_ID      10600 non-null  float64
 10  LOCATION_ID_1    10600 non-null  float64
 11  CITY             10600 non-null  object
 12  COUNTRY_ID       10600 non-null  object
 13  STATE_PROVINCE   10600 non-null  object
 14  STREET_ADDRESS   10600 non-null  object
 15  COUNTRY_ID_1     10600 non-null  object
 16  COUNTRY_NAME     10600 non-null  object
 17  REGION_ID        10600 non-null  float64
 18  REGION_ID_1      10600 non-null  float64
 19  REGION_NAME      10600 non-null  object
 20  JOB_ID           10600 non-null  object
dtypes: float64(8), object(13)
memory usage: 1.7+ MB

In [ ]:
df.DEPARTMENT_ID.unique()

array([ 60.,  50.,  10.,  30.,  90., 100., 110.,  20.,  40.,  80.,  70.])

In [ ]:
df.EMPLOYEE_ID.unique()

array([103., 104., 105., 106., 107., 120., 121., 122., 123., 124., 125.,
       126., 127., 128., 129., 130., 131., 132., 133., 134., 135., 136.,
       137., 138., 139., 140., 141., 142., 143., 144., 180., 181., 182.,
       183., 184., 185., 186., 187., 188., 189., 190., 191., 192., 193.,
       194., 195., 196., 197., 198., 199., 200., 114., 115., 116., 117.,
       118., 119., 100., 101., 102., 108., 109., 110., 111., 112., 113.,
       205., 206., 201., 202., 203., 145., 146., 147., 148., 149., 150.,
       151., 152., 153., 154., 155., 156., 157., 158., 159., 160., 161.,
       162., 163., 164., 165., 166., 167., 168., 169., 170., 171., 172.,
       173., 174., 175., 176., 177., 179., 204.])

In [ ]:
df.EMPLOYEE_ID.value_counts()

157.0    100
149.0    100
136.0    100
122.0    100
108.0    100
        ...
134.0    100
159.0    100
194.0    100
206.0    100
104.0    100
Name: EMPLOYEE_ID, Length: 106, dtype: int64

In [ ]:
df[df.EMPLOYEE_ID == 157.0]

       EMPLOYEE_ID  DEPARTMENT_ID  ...             REGION_NAME  JOB_ID
1787         157.0           80.0  ...                  Europe  SA_REP
1821         157.0           80.0  ...                  Europe  SA_REP
1855         157.0           80.0  ...                  Europe  SA_REP
1889         157.0           80.0  ...                  Europe  SA_REP
1923         157.0           80.0  ...                  Europe  SA_REP
...            ...            ...  ...                     ...     ...
10417        157.0           80.0  ...  Middle East and Africa  SA_REP
10451        157.0           80.0  ...  Middle East and Africa  SA_REP
10485        157.0           80.0  ...  Middle East and Africa  SA_REP
10519        157.0           80.0  ...  Middle East and Africa  SA_REP
10553        157.0           80.0  ...  Middle East and Africa  SA_REP

[100 rows x 21 columns]

In [ ]:
len(df.LAST_NAME.unique())

102

In [ ]:
df.LAST_NAME.unique()

array(['Hunold', 'Ernst', 'Austin', 'Pataballa', 'Lorentz', 'Weiss',
       'Fripp', 'Kaufling', 'Vollman', 'Mourgos', 'Nayer', 'Mikkilineni',
       'Landry', 'Markle', 'Bissot', 'Atkinson', 'Marlow', 'Olson',
       'Mallin', 'Rogers', 'Gee', 'Philtanker', 'Ladwig', 'Stiles', 'Seo',
       'Patel', 'Rajs', 'Davies', 'Matos', 'Vargas', 'Taylor', 'Fleaur',
       'Sullivan', 'Geoni', 'Sarchand', 'Bull', 'Dellinger', 'Cabrio',
       'Chung', 'Dilly', 'Gates', 'Perkins', 'Bell', 'Everett', 'McCain',
       'Jones', 'Walsh', 'Feeney', 'OConnell', 'Grant', 'Whalen',
       'Raphaely', 'Khoo', 'Baida', 'Tobias', 'Himuro', 'Colmenares',
       'King', 'Kochhar', 'De Haan', 'Greenberg', 'Faviet', 'Chen',
       'Sciarra', 'Urman', 'Popp', 'Higgins', 'Gietz', 'Hartstein', 'Fay',
       'Mavris', 'Russell', 'Partners', 'Errazuriz', 'Cambrault',
       'Zlotkey', 'Tucker', 'Bernstein', 'Hall', 'Olsen', 'Tuvault',
       'Sully', 'McEwen', 'Smith', 'Doran', 'Sewall', 'Vishney', 'Greene',
       'Marvins', 'Lee', 'Ande', 'Banda', 'Ozer', 'Bloom', 'Fox', 'Bates',
       'Kumar', 'Abel', 'Hutton', 'Livingston', 'Johnson', 'Baer'],
      dtype=object)

In [ ]:
len(df.FIRST_NAME.unique())

90

In [ ]:
len(df.EMAIL.unique())

106

In [ ]:
len(df.PHONE_NUMBER.unique())

106

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10600 entries, 0 to 10599
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EMPLOYEE_ID      10600 non-null  float64
 1   DEPARTMENT_ID    10600 non-null  float64
 2   EMAIL            10600 non-null  object
 3   FIRST_NAME       10600 non-null  object
 4   LAST_NAME        10600 non-null  object
 5   PHONE_NUMBER     10600 non-null  object
 6   SALARY           10600 non-null  float64
 7   DEPARTMENT_ID_1  10600 non-null  float64
 8   DEPARTMENT_NAME  10600 non-null  object
 9   LOCATION_ID      10600 non-null  float64
 10  LOCATION_ID_1    10600 non-null  float64
 11  CITY             10600 non-null  object
 12  COUNTRY_ID       10600 non-null  object
 13  STATE_PROVINCE   10600 non-null  object
 14  STREET_ADDRESS   10600 non-null  object
 15  COUNTRY_ID_1     10600 non-null  object
 16  COUNTRY_NAME     10600 non-null  object
 17  REGION_ID        10600 non-null  float64
 18  REGION_ID_1      10600 non-null  float64
 19  REGION_NAME      10600 non-null  object
 20  JOB_ID           10600 non-null  object
dtypes: float64(8), object(13)
memory usage: 1.7+ MB

In [ ]:
df.drop(columns=['EMPLOYEE_ID','EMAIL','FIRST_NAME','LAST_NAME','PHONE_NUMBER'],axis=1,inplace=True)
df.head()

   DEPARTMENT_ID  SALARY  DEPARTMENT_ID_1  ... REGION_ID_1  REGION_NAME   JOB_ID
0           60.0  9000.0             60.0  ...         1.0       Europe  IT_PROG
1           60.0  6000.0             60.0  ...         1.0       Europe  IT_PROG
2           60.0  4800.0             60.0  ...         1.0       Europe  IT_PROG
3           60.0  4800.0             60.0  ...         1.0       Europe  IT_PROG
4           60.0  4200.0             60.0  ...         1.0       Europe  IT_PROG

[5 rows x 16 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10600 entries, 0 to 10599
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DEPARTMENT_ID    10600 non-null  float64
 1   SALARY           10600 non-null  float64
 2   DEPARTMENT_ID_1  10600 non-null  float64
 3   DEPARTMENT_NAME  10600 non-null  object
 4   LOCATION_ID      10600 non-null  float64
 5   LOCATION_ID_1    10600 non-null  float64
 6   CITY             10600 non-null  object
 7   COUNTRY_ID       10600 non-null  object
 8   STATE_PROVINCE   10600 non-null  object
 9   STREET_ADDRESS   10600 non-null  object
 10  COUNTRY_ID_1     10600 non-null  object
 11  COUNTRY_NAME     10600 non-null  object
 12  REGION_ID        10600 non-null  float64
 13  REGION_ID_1      10600 non-null  float64
 14  REGION_NAME      10600 non-null  object
 15  JOB_ID           10600 non-null  object
dtypes: float64(7), object(9)
memory usage: 1.3+ MB

In [ ]:
deptname = pd.get_dummies(df.DEPARTMENT_NAME,prefix='depname')
deptname.head()

   depname_Accounting  depname_Administration  ...  depname_Sales  depname_Shipping
0                   0                       0  ...              0                 0
1                   0                       0  ...              0                 0
2                   0                       0  ...              0                 0
3                   0                       0  ...              0                 0
4                   0                       0  ...              0                 0

[5 rows x 11 columns]

In [ ]:
catcols = df.dtypes[df.dtypes =='object'].index.tolist()
catcols

['DEPARTMENT_NAME',
 'CITY',
 'COUNTRY_ID',
 'STATE_PROVINCE',
 'STREET_ADDRESS',
 'COUNTRY_ID_1',
 'COUNTRY_NAME',
 'REGION_NAME',
 'JOB_ID']

In [ ]:

def onehotfun(df,catcol):
  onehotdummies = []
  onehotdummies.append(df)
  for cat in catcol:
    catname = pd.get_dummies(df[cat],prefix=cat)
    onehotdummies.append(catname)

  dffinal = pd.concat(onehotdummies,axis=1)
  dffinal.drop(columns=catcol, axis=1, inplace=True)
  return dffinal

In [ ]:
finaldf = onehotfun(df,catcols)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10600 entries, 0 to 10599
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DEPARTMENT_ID    10600 non-null  float64
 1   SALARY           10600 non-null  float64
 2   DEPARTMENT_ID_1  10600 non-null  float64
 3   DEPARTMENT_NAME  10600 non-null  object
 4   LOCATION_ID      10600 non-null  float64
 5   LOCATION_ID_1    10600 non-null  float64
 6   CITY             10600 non-null  object
 7   COUNTRY_ID       10600 non-null  object
 8   STATE_PROVINCE   10600 non-null  object
 9   STREET_ADDRESS   10600 non-null  object
 10  COUNTRY_ID_1     10600 non-null  object
 11  COUNTRY_NAME     10600 non-null  object
 12  REGION_ID        10600 non-null  float64
 13  REGION_ID_1      10600 non-null  float64
 14  REGION_NAME      10600 non-null  object
 15  JOB_ID           10600 non-null  object
dtypes: float64(7), object(9)
memory usage: 1.3+ MB

In [ ]:
finaldf.head()

   DEPARTMENT_ID  SALARY  ...  JOB_ID_ST_CLERK  JOB_ID_ST_MAN
0           60.0  9000.0  ...                0              0
1           60.0  6000.0  ...                0              0
2           60.0  4800.0  ...                0              0
3           60.0  4800.0  ...                0              0
4           60.0  4200.0  ...                0              0

[5 rows x 115 columns]

In [ ]:
finaldf.DEPARTMENT_ID.unique()

array([ 60.,  50.,  10.,  30.,  90., 100., 110.,  20.,  40.,  80.,  70.])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
finaldf.to_csv('/content/drive/MyDrive/Employee_Cleanup.csv', index=False)