In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/Manju410/MLPractice/main/Car_Project/Car%20details%20v3.csv")
df.head()

                           name  year  ...                    torque  seats
0        Maruti Swift Dzire VDI  2014  ...            190Nm@ 2000rpm    5.0
1  Skoda Rapid 1.5 TDI Ambition  2014  ...       250Nm@ 1500-2500rpm    5.0
2      Honda City 2017-2020 EXi  2006  ...     12.7@ 2,700(kgm@ rpm)    5.0
3     Hyundai i20 Sportz Diesel  2010  ...  22.4 kgm at 1750-2750rpm    5.0
4        Maruti Swift VXI BSIII  2007  ...     11.5@ 4,500(kgm@ rpm)    5.0

[5 rows x 13 columns]

1. Maximum Cars sold out based on seats parameter.
  - 4 seats : honda
  - 5 seats : Toyota
2. which model of the car sold max in last year(assumption).
  - Honda: 14 
3. Which model of car sold max in based on fuel type since last year.
  - Toyota : 15 : petrol
  - Renult : 20: disel
4. Average selling car price depend on owner type and how much km driven
  - 4.5L : first owner: 60k
  - 9L   : Second owner: 1L
  - 3-5L : 80k avg : first owner: 20
5. life span of the cars based on owner type
  - swift : 30 : Fourth owner
  - hundai : 25 : Fourth owner
  - toyota : 20: Fourth owner
    - swift is better life span
6. comparing selling price from buying from individual or by dealer based on model
  - 4.5L : individual: swift
  - 5L : dealer : honda
7. how car price differ from car torque and speed based on model
  - 8L : 25nm- 2500rpm : kia
  - 6L : 150nm- 3000rpm : benz
8. cost of the car will vary depend on transmission type and model.
  - 10L : Automative : bmw
  - 9L : Manual :hundai
9. is that car price reducing depend on year and type
  - 4L : 2014: honda
  - 3L : 2013: kia
10. what is the milage depend on hp and engine type
  - 20kmpl : 70bhp- 1200cc
  - 15kmpl : 60bhp- 1100cc

In [4]:
df.shape

(8128, 13)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

#comparing selling price from buying from individual or by dealer based on model
-4.5L : individual: swift
-5L : dealer : honda

In [6]:
df.head()

                           name  year  ...                    torque  seats
0        Maruti Swift Dzire VDI  2014  ...            190Nm@ 2000rpm    5.0
1  Skoda Rapid 1.5 TDI Ambition  2014  ...       250Nm@ 1500-2500rpm    5.0
2      Honda City 2017-2020 EXi  2006  ...     12.7@ 2,700(kgm@ rpm)    5.0
3     Hyundai i20 Sportz Diesel  2010  ...  22.4 kgm at 1750-2750rpm    5.0
4        Maruti Swift VXI BSIII  2007  ...     11.5@ 4,500(kgm@ rpm)    5.0

[5 rows x 13 columns]

In [8]:
df.seller_type.unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [15]:
df.name.unique()[:100]

array(['Maruti Swift Dzire VDI', 'Skoda Rapid 1.5 TDI Ambition',
       'Honda City 2017-2020 EXi', 'Hyundai i20 Sportz Diesel',
       'Maruti Swift VXI BSIII', 'Hyundai Xcent 1.2 VTVT E Plus',
       'Maruti Wagon R LXI DUO BSIII', 'Maruti 800 DX BSII',
       'Toyota Etios VXD', 'Ford Figo Diesel Celebration Edition',
       'Renault Duster 110PS Diesel RxL', 'Maruti Zen LX',
       'Maruti Swift Dzire VDi', 'Maruti Swift 1.3 VXi',
       'Maruti Wagon R LXI Minor', 'Mahindra KUV 100 mFALCON G80 K8 5str',
       'Maruti Ertiga SHVS VDI', 'Hyundai i20 1.4 CRDi Asta',
       'Maruti Alto LX', 'Hyundai i20 2015-2017 Asta 1.4 CRDi',
       'Mahindra Verito 1.5 D4 BSIII', 'Honda WR-V i-DTEC VX',
       'Maruti Swift Dzire ZDI', 'Maruti SX4 ZDI',
       'Tata Tigor 2017-2020 XZ', 'Maruti Baleno Delta 1.2',
       'Maruti Alto 800 LXI', 'Chevrolet Enjoy TCDi LTZ 7 Seater',
       'Maruti Omni E MPI STD BS IV', 'Maruti Vitara Brezza LDi Option',
       'Fiat Palio 1.2 ELX', 'Maruti Omni 8 Seater BSIV',
       'Hyundai i20 1.2 Asta Dual Tone', 'Maruti Vitara Brezza LDi',
       'Maruti Alto 800 CNG LXI Optional', 'Maruti Alto K10 VXI Airbag',
       'Hyundai Verna VTVT 1.6 SX Option', 'Datsun GO D',
       'Tata Safari DICOR 2.2 LX 4x2', 'Maruti 800 Std',
       'Jeep Compass 1.4 Limited Plus BSIV', 'Honda City i VTEC VX',
       'Honda City V MT', 'Maruti Swift Dzire VXi AT',
       'Maruti Vitara Brezza VDi', 'Maruti Alto K10 VXI',
       'Toyota Fortuner 4x4 MT',
       'Toyota Innova 2.5 G (Diesel) 7 Seater BS IV',
       'Mercedes-Benz B Class B180', 'Honda Amaze S Diesel',
       'Mitsubishi Pajero Sport 4X4', 'Honda City i DTEC S',
       'Maruti Ciaz Zeta', 'Honda Jazz VX Diesel',
       'Toyota Innova Crysta 2.8 ZX AT BSIV',
       'Toyota Innova 2.5 G (Diesel) 7 Seater',
       'Audi A6 2.0 TDI Technology', 'Toyota Corolla Altis 1.8 VL CVT',
       'Audi A6 2.0 TDI  Design Edition',
       'Mercedes-Benz New C-Class 220 CDI AT',
       'Tata Manza ELAN Quadrajet BS IV', 'Hyundai i10 Magna',
       'Hyundai i20 Asta 1.4 CRDi', 'Ford Figo 1.2P Titanium MT',
       'Volkswagen Ameo 1.5 TDI Highline 16 Alloy',
       'Honda City i DTEC VX', 'Maruti Wagon R AMT VXI',
       'Volkswagen Ameo 1.5 TDI Comfortline',
       'Maruti Vitara Brezza ZDi Plus AMT', 'Maruti Swift VDI Deca',
       'Maruti Swift Star VDI', 'Maruti Ertiga ZXI', 'Tata Indica DLS',
       'Volkswagen Vento Diesel Highline',
       'Toyota Innova 2.5 VX (Diesel) 8 Seater',
       'Ford EcoSport 1.5 TDCi Titanium Plus BSIV',
       'BMW X1 sDrive20i xLine', 'Maruti Celerio ZXI MT BSIV',
       'Datsun GO A Petrol', 'Maruti Alto 800 VXI BSIV',
       'Maruti Alto 800 LXI BSIV', 'Maruti Swift VDI BSIV W ABS',
       'Hyundai i10 Era 1.1', 'Maruti Wagon R LXI LPG BSIV',
       'Volkswagen Polo 1.2 MPI Comfortline', 'Hyundai i10 Magna 1.1L',
       'Volkswagen Vento Petrol Highline', 'Maruti Zen Estilo LXI BSIII',
       'Hyundai i20 Asta Optional with Sunroof 1.2',
       'Maruti Swift Dzire LDI', 'Hyundai Xcent 1.2 Kappa SX Option AT',
       'Maruti Alto LX BSIII', 'Hyundai i20 1.4 Asta Option',
       'Maruti Wagon R VXI', 'Tata Manza Aura (ABS) Quadrajet',
       'Maruti Swift VXI', 'Maruti Eeco 7 Seater Standard BSIV',
       'Maruti Baleno Zeta 1.2', 'Mahindra Scorpio VLX AT AIRBAG BSIV',
       'Ford Freestyle Titanium Petrol BSIV'], dtype=object)